kind: pipeline
name: default

steps:
- name: test
  image: golang:1.13
  volumes:
  - name: deps
    path: /go
  commands:
  - go test

- name: build
  image: golang:1.13
  volumes:
  - name: deps
    path: /go
  commands:
  - go build test.go
  - ./test

volumes:
- name: deps
  temp: {}
  
